const DealsList = [
  {
    id: 1,
    title: "Dawlence Chrome Fridge",
    category: "Electronics",
    name: "Fridge",

    description: "Dawlence Chrome Series Fridge.",
    features: ["Invertor", "Glass Door", "3-year warranty"],
    price: "Rs. 50,000",
    discount: "10% OFF",
    image: require("../assets/Deals/fridge1.png"),
  },
  {
    id: 2,
    category: "Electronics",
    name: "Fridge",
    title: "Dawlence Avante+ Fridge",
    description: "Dawlence Avante+ Series Fridge.",
    features: ["Invertor", "Glass Door", "3-year warranty,"],
    price: "Rs. 150,000",
    discount: "15% OFF",
    image: require("../assets/Deals/fridge2.png"),
  },
  {
    id: 3,
    category: "Phones",
    name: "Phone",
    title: "Samsung S23",
    description: "Samsung S23 (12GB, 256GB)",
    features: ["12GB", "Blue Color", "3-year warranty,"],
    price: "Rs. 170,000",
    discount: "5% OFF",
    image: require("../assets/Deals/phone.png"),
  },
  {
    id: 4,
    categories: "Phones",
    name: "Phone",
    title: "Redmi 13C",
    description: "Redmi 13C (4GB, 64GB)",
    features: ["4GB", "White Color", "50MP Camera"],
    price: "Rs. 80,000",
    discount: "18% OFF",
    image: require("../assets/Deals/phone2.png"),
  },
  {
    id: 5,
    category: "Furniture",
    name: "Sofa",
    title: "Velvet Sofa",
    description: "Velvet Sofa (6 Seater)",
    features: ["Velvet Material", "Sky Blue", "6 Seater"],
    price: "Rs. 85,000",
    discount: "18% OFF",
    image: require("../assets/Deals/sofa.png"),
  },
  {
    id: 6,
    category: "Electronics",
    name: "Washing Machine",
    title: "Samsung Washing Machine",
    description: "Samsung Washing Machine (10KG)",
    features: ["10KG", "White Color", "3-year warranty"],
    price: "Rs. 65,000",
    discount: "10% OFF",
    image: require("../assets/Deals/washing.png"),
  },
];

export default DealsList;
