const Products = [
  {
    id: 1,
    category: "Electronics",
    name: "Fridges",
    title: "Dawlence Chrome Fridge",
    description: "Dawlence Chrome Series Fridge.",
    features: ["Invertor", "Glass Door", "3-year warranty"],
    price: "Rs. 50,000",
    discount: "15% OFF",
    image: require("../assets/Deals/fridge1.png"),
    sold: 5,
  },
  {
    id: 2,
    category: "Electronics",
    name: "Fridges",
    title: "Dawlence Avante+ Fridge",
    description: "Dawlence Avante+ Series Fridge.",
    features: ["Invertor", "Glass Door", "3-year warranty,"],
    price: "Rs. 150,000",
    discount: "",
    image: require("../assets/Deals/fridge2.png"),
    sold: 10,
  },
  {
    id: 3,
    category: "Phones & Accessories",
    name: "Mobile Phones",
    title: "Samsung S23",
    description: "Samsung S23 (12GB, 256GB)",
    features: ["12GB", "Blue Color", "3-year warranty,"],
    price: "Rs. 170,000",
    discount: "",
    image: require("../assets/Deals/phone.png"),
    sold: 15,
  },
  {
    id: 4,
    category: "Phones & Accessories",
    name: "Mobile Phones",
    title: "Redmi 13C",
    description: "Redmi 13C (4GB, 64GB)",
    features: ["4GB", "White Color", "50MP Camera"],
    price: "Rs. 80,000",
    discount: "15% OFF",
    image: require("../assets/Deals/phone2.png"),
    sold: 20,
  },
  {
    id: 5,
    category: "Furniture",
    name: "Sofa, Bed & Tables",
    title: "Velvet Sofa",
    description: "Velvet Sofa (6 Seater)",
    features: ["Velvet Material", "Sky Blue", "6 Seater"],
    price: "Rs. 85,000",
    discount: "",
    image: require("../assets/Deals/sofa.png"),
    sold: 25,
  },
  {
    id: 6,
    category: "Electronics",
    name: "Washing Machines",
    title: "Samsung Washing Machine",
    description: "Samsung Washing Machine (10KG)",
    features: ["10KG", "White Color", "3-year warranty"],
    price: "Rs. 65,000",
    discount: "",
    image: require("../assets/Deals/washing.png"),
    sold: 0,
  },
  {
    id: 7,
    category: "Phones & Accessories",
    name: "Mobile Accessories",
    title: "AKG Handfrees",
    description:
      "AKG Earphones. Original AKG Earphones. Handsfree with Top Base",
    features: ["3.5mm Jack", "Black Color", "2-months warranty,"],
    price: "Rs. 500",
    discount: "",
    image: require("../assets/Deals/handfree.png"),
    sold: 25,
  },
  {
    id: 8,
    category: "Phones & Accessories",
    name: "Mobile Accessories",
    title: "Sony Wireless HeadPhones",
    description:
      "Sony Wireless HeadPhones. Original Sony HeadPhones. Long lasting battery",
    features: ["Wireless", "Multiple Colors", "2-year warranty,"],
    price: "Rs. 30,000",
    discount: "",
    image: require("../assets/Deals/headphones.png"),
    sold: 60,
  },
];

export default Products;
